In [4]:
import numpy as np
from L1_adapt import L1_adapt
def f(x):
    Am = np.array([[0,1,0,0],[0,0, 0, -9.8],[0, 0, 0, 32.667],[0, 0, 1, 0]])
    return np.matmul(Am,x)

def g(x):
    Bm = np.array([[0,2,-3.33,0]]).T
    return Bm

x = np.array([[0,0,0,0]]).T
u_l1 = 0
a = L1_adapt(f,g,x,u_l1)
xlog = []
ulog = []
kg =np.array([-1.0000, -2.1244, -5.4229, -27.0133])



for t in range(1000):
    x,u_l1 = a.get_next_x_u(x, u_l1+kg@x)
    xlog.append(x[3])
    ulog.append(u_l1+kg@x)
print(ulog)


[array([[-1.39081868]]), array([[28.79556744]]), array([[-547.99244445]]), array([[10411.88438047]]), array([[-197828.91504914]]), array([[3758751.76620421]]), array([[-71416285.70215856]]), array([[1.35690943e+09]]), array([[-2.57812792e+10]]), array([[4.89844304e+11]]), array([[-9.30704178e+12]]), array([[1.76833794e+14]]), array([[-3.35984208e+15]]), array([[6.38369996e+16]]), array([[-1.21290299e+18]]), array([[2.30451569e+19]]), array([[-4.3785798e+20]]), array([[8.31930162e+21]]), array([[-1.58066731e+23]]), array([[3.00326789e+24]]), array([[-5.70620898e+25]]), array([[1.08417971e+27]]), array([[-2.05994144e+28]]), array([[3.91388874e+29]]), array([[-7.43638861e+30]]), array([[1.41291384e+32]]), array([[-2.68453629e+33]]), array([[5.10061895e+34]]), array([[-9.691176e+35]]), array([[1.84132344e+37]]), array([[-3.49851454e+38]]), array([[6.64717762e+39]]), array([[-1.26296375e+41]]), array([[2.39963112e+42]]), array([[-4.55929913e+43]]), array([[8.66266834e+44]]), array([[-1.6459

In [14]:
from scipy.linalg import inv, null_space
def f(x):
    Am = np.array([[0,1,0,0],[0,0, 0, -9.8],[0, 0, 0, 32.667],[0, 0, 1, 0]])
    return np.matmul(Am,x)

def g(x):
    Bm = np.array([[0,2,-3.33,0]]).T
    return Bm

x = np.array([[0,0,0,0]]).T
u = 0

a = L1_adapt(f,g,x,u)
Ts = 0.01
g=g(x)
g_perp = null_space(g.T)

gg = np.concatenate((g,g_perp),axis=1)

x_tilde = np.array([[0.1,0,0,0.1]]).T
As = -10*np.eye(4)

sm, s_um = a.adaptive_law(gg, x_tilde,As,Ts, 4,1)
print(sm)
print(s_um)

[[-3.39360488e-16]]
[[ 4.89559565]
 [-8.15116676]
 [-9.50833194]]


In [42]:

g_perp = np.array([[1, 0, 0],[0, 0, -float(g[2])],[0, 0, float(g[1])],[0, 1, 0]])
g_perp

array([[1.  , 0.  , 0.  ],
       [0.  , 0.  , 3.33],
       [0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  ]])

In [47]:
from scipy.linalg import expm
Ts = 0.01
As = -10*np.eye(4)
Mat_expm = expm(As*0.01)
Phi = inv(As) * (Mat_expm - np.eye(4))
adapt_gain = -inv(Phi)*Mat_expm

gg = np.concatenate((g,g_perp),axis=1)
sigma_hat = inv(gg) @ adapt_gain @ x_tilde
print(sigma_hat[0:1])

[[0.]]


In [46]:
sigma_hat_m = np.zeros(shape = (1,1))
sigma_hat_m

array([[0.]])